<?php
use Illuminate\Database\Seeder;
class SubforumsTableSeeder extends Seeder{
	public function run(){
		DB::table('forum_subforums')->delete();
		DB::table('forum_subforums')->
			insert([
				[
					'name'        =>'Official',
					'description' =>'The official forums for RuneTime Information',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>-1,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'RuneTime Community',
					'description' =>'',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>-1,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'RuneScape',
					'description' =>'',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>-1,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Old-School RuneScape',
					'description' =>'',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>-1,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Team Leader',
					'description' =>'',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>-1,
					'roles'       =>json_encode([1,2,4,6,8,10,12]),
				],
				[
					'name'        =>'Staff Only',
					'description' =>'',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>-1,
					'roles'       =>json_encode([1,2,3,4,5,6,7,8,9,10,11,12,13]),
				],
				[
					'name'        =>'RuneTime News & Updates',
					'description' =>'Visit here to check out all the News and Updates happening on RuneTime!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>1,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Website Discussion & Feedback',
					'description' =>'Come here to discuss all your feedback towards RuneTime\'s website!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>1,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'How Did You Find Us?',
					'description' =>'Let us know how you found our fansite! Friend? YouTube? Jagex?',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>1,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'RuneTime Finances',
					'description' =>'So everyone know where donations and money is being spent!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>1,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Official Events',
					'description' =>'All official RuneTime events are posted in here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>0,
					'parent'      =>1,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Introductions',
					'description' =>'If you\'re new to RuneTime, introduce yourself here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>1,
					'parent'      =>2,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Support',
					'description' =>'If you need support please post in here, or use a ticket or even pm us!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>2,
					'parent'      =>2,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Games & Entertainment',
					'description' =>'Slightly bored at the minute? Come visit this forum for some text/forum based games and you\'ll never be bored again! You will not receive post count posting in here.',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>3,
					'parent'      =>2,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Hobbies & Interests',
					'description' =>'Discuss all your non-related hobbies & interests here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>4,
					'parent'      =>2,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Off-Topic',
					'description' =>'No topics on our forums which tie into your topic? If not, post it here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>5,
					'parent'      =>2,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Pictures and Graphics',
					'description' =>'Drawing pictures? Opening a graphics store? If so, post them all here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>6,
					'parent'      =>2,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Music & Videos',
					'description' =>'Share with us all your favourite music and videos!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>7,
					'parent'      =>2,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Member Events',
					'description' =>'Having a 99 Party? 120 Party? All RuneTime community events can be posted in here.',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>8,
					'parent'      =>2,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'User Guides',
					'description' =>'Post your guides in here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>9,
					'parent'      =>2,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'RuneScape News & Updates',
					'description' =>'Find out about all the latest news and updates to do with RuneScape here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>1,
					'parent'      =>3,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'General Discussion',
					'description' =>'Got something to say relating RuneScape but not fitting in to any other forum? Post it here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>2,
					'parent'      =>3,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Personal Goals & Achievements',
					'description' =>'Share your current goal with us here! Did you finally reach that goal? share it here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>3,
					'parent'      =>3,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'PvP & PvM Discussion',
					'description' =>'If you\'re interested in PvP or PvM, or even both, this is the forum for you!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>4,
					'parent'      =>3,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Market',
					'description' =>'Cannot buy something at the Grand Exchange? Or maybe you\'ve reached your daily peak limits. Purchase and sell your RuneScape goods here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>5,
					'parent'      =>3,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Quests & Trails',
					'description' =>'Anything and everything to do with Quests and Treasure Trails are posted here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>6,
					'parent'      =>3,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Other Great Fansites',
					'description' =>'Check here to see what other fansites we recommend you check out!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>7,
					'parent'      =>3,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Clan System',
					'description' =>'Interested in joining our RuneTime Clan? Wanting some clan-information? Or looking to do something with a different Clan? This is the place to be!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>8,
					'parent'      =>3,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Old-School News & Updates',
					'description' =>'Are you a fan of the 2007 days? Well, check here and we\'ll keep you posted on all the updates to do with Old-School RuneScape!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>1,
					'parent'      =>4,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'General Discussion',
					'description' =>'Got something to say relating Old-School RuneScape but not fitting in to any other forum? Post it here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>2,
					'parent'      =>4,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Personal Goals & Achievements',
					'description' =>'Finally got that 99 you so desperately wanted? Oh wait, you got that Dragon dagger? POST HERE!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>3,
					'parent'      =>4,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'PvP & PvM Discussion',
					'description' =>'If you\'re interested in Old-School PvP or PvM, or even both, this is the forum for you!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>4,
					'parent'      =>4,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Market',
					'description' =>'No Grand Exchange? So what! Purchase and sell your Old-School goods here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>5,
					'parent'      =>4,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Quests & Trails',
					'description' =>'Congratulations! Completing quests and trails on Old-School are difficult! Wait, you\'re experiencing problems with them? If you\'re proud, or in desperate need of help, post here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>6,
					'parent'      =>4,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'General Chat',
					'description' =>'Anything that can only be discussed between team leaders and admins can be posted in here.',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>1,
					'parent'      =>5,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Staff Trouble',
					'description' =>'If you\'re having problems with a staff member in your team please post it in here.',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>2,
					'parent'      =>5,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Admin Help',
					'description' =>'If you require assistance off an administrator post in here.',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>3,
					'parent'      =>5,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Promotions',
					'description' =>'If you would like to promote a staff member in your team you can do so in here.',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>4,
					'parent'      =>5,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Suggestions',
					'description' =>'If you have a suggestion that you wish to only share with the admins and team leaders post it in here.',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>5,
					'parent'      =>5,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Important Details',
					'description' =>'Look here constantly to make sure details for specific utilities have not been changed!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>1,
					'parent'      =>6,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Discussions & Announcements',
					'description' =>'Discuss all the new updates to RuneTime with you friends and colleagues!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>2,
					'parent'      =>6,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Site Suggestions',
					'description' =>'Suggest ideas to be inserted into RuneTime\'s website here!',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>3,
					'parent'      =>6,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Staff Lounge',
					'description' =>'Come here to chill with your staff members, and play a game or two. Or maybe just discuss about that movie you saw last night without any other member seeing.',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>4,
					'parent'      =>6,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'Away From Website Notice',
					'description' =>'Post in here if you are going to be off the website for a while.',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>5,
					'parent'      =>6,
					'roles'       =>json_encode([]),
				],
				[
					'name'        =>'DJ Message',
					'description' =>'Most recent TOPIC TITLE gets copied to the radio page... (The actual forum posting is ignored, just the TOPIC TITLE is used. Replying to a topic also makes it the most recent, so you can re-use postings by simply replying. Remember to turn an AutoDJ Message on when you finish DJing)',
					'threads'     =>0,
					'posts'     =>0,
					'last_post'   =>-1,
					'position'    =>6,
					'parent'      =>6,
					'roles'       =>json_encode([1,2,3]),
				],
			]);
	}
}