language: php

env:
  - DB_USERNAME: root
  - DB_DATABASE: runetime

php:
  - 5.6

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

before_script:
  - mysql -e 'create database runetime;'

script: vendor/bin/phpunit
