@extends('layouts.settings')
@section('settings')
						<h3>
							@lang('settings.password.note')
						</h3>
						@lang('settings.password.current')
						@lang('settings.password.new')
						@lang('settings.password.confirm_new')
@stop