@extends('...layouts.default')
@section('contents')
			<div class='wrapper'>
				<h1>
					@lang('about.name')
				</h1>
				<p class='lead'>
					@lang('about.b1.p1')
				</p>
				<p>
					@lang('about.b1.p2')
				</p>
				<dl>
					<dt>
						@lang('about.b1.p3')
					</dt>
					<dd>
						@lang('about.b1.p4')
					</dd>
					<dt>
						@lang('about.b1.p5')
					</dt>
					<dd>
						@lang('about.b1.p6')
					</dd>
					<dt>
						@lang('about.b1.p7')
					</dt>
					<dd>
						@lang('about.b1.p8')
					</dd>
					<dt>
						@lang('about.b1.p9')
					</dt>
					<dd>
						@lang('about.b1.p10')
					</dd>
					<dt>
						@lang('about.b1.p11')
					</dt>
					<dd>
						@lang('about.b1.p12')
					</dd>
					<dt>
						@lang('about.b1.p13')
					</dt>
					<dd>
						@lang('about.b1.p14')
					</dd>
				</dl>
				<h2>
					@lang('about.b2.name')
				</h2>
				<p>
					@lang('about.b2.p1')
				</p>
				<img src='/img/about/setup.png' alt='How We Are Setup' class='center-block img-responsive' />
				<p>
					@lang('about.b2.p2')
				</p>
				<h2>
					@lang('about.b3.name')
				</h2>
				<p>
					@lang('about.b3.p1')
				</p>
				<p>
					@lang('about.b3.p2')
				</p>
				<p>
					@lang('about.b3.p3') <a href='http://services.runescape.com/m=rswiki/en/Rules_of_RuneScape' target='_blank' title='Rules of RuneScape'>http://services.runescape.com/m=rswiki/en/Rules_of_RuneScape</a>
				</p>
				<p>
					@lang('about.b3.p4')
				</p>
			</div>
@stop